import { DISTRICTS, VIEW_BOX } from '../lib/pragueDistricts';

/**
 * A flat, click-to-select map of Prague's ten municipal districts, shown beside
 * the checkbox list on the `casti` question.
 *
 * It is inline SVG generated by `scripts/build-district-map.js` from real
 * OpenStreetMap boundaries — no tiles, no mapping library, no network call at
 * render time, and nothing to rate-limit. That also means it costs nothing on a
 * phone and works offline, unlike `SchoolMap.jsx` which does fetch OSM tiles.
 *
 * ⚠️ The SVG is deliberately `aria-hidden`. Every district here is also a real
 * checkbox in the list next to it, so exposing both would double every option
 * to a screen reader — ten districts announced as twenty controls, with two tab
 * stops each and no way to tell which is which. The checkboxes are the
 * accessible path; this is a faster pointer-driven shortcut onto the same
 * state. If the checkbox list is ever removed, this has to grow real
 * `role="checkbox"` semantics and keyboard handling before it can stand alone.
 *
 * `hovered`/`onHover` link the map to the checkbox list in both directions:
 * pointing at either one highlights the other. That is the whole reason a map
 * is here rather than just the list — a student who does not already know
 * Prague's numbering can hover "Praha 6" and see *where* Praha 6 is, and hover
 * a shape to find out what it is called. Pointer-only by nature, so it is
 * purely additive: nothing about touch or keyboard use depends on it.
 */
/**
 * How big the number can be without spilling out of its own district.
 *
 * `labelR` is the distance from the label point to the nearest edge, measured
 * when the geometry was generated. The 22 správní obvody differ hugely in size
 * — Praha 2 has 21.8 units of room, Praha 22 has 70.2 — so a single font size
 * either overflows the small ones or looks lost in the big ones. Clamped at
 * both ends: never so small it stops being readable, never so large that a
 * two-digit number starts competing with the shape it sits on.
 */
function labelSize(district) {
  return Math.round(Math.min(26, Math.max(13, district.labelR * 0.72)));
}

function DistrictMap({ selected = [], onToggle, max, hovered, onHover }) {
  const chosen = new Set(selected);
  const atMax = typeof max === 'number' && chosen.size >= max;

  return (
    <div className="district-map">
      <svg
        className="district-map-svg"
        viewBox={VIEW_BOX}
        aria-hidden="true"
        focusable="false"
      >
        {DISTRICTS.map((district) => {
          const isSelected = chosen.has(district.id);
          // Past the cap an unselected district stops responding, matching how
          // the option chips dim rather than silently ignoring the click.
          const isBlocked = atMax && !isSelected;

          return (
            <g
              key={district.id}
              className={[
                'district-map-region',
                isSelected ? 'is-selected' : '',
                isBlocked ? 'is-blocked' : '',
                hovered === district.id ? 'is-peer-hovered' : '',
              ]
                .filter(Boolean)
                .join(' ')}
              onClick={isBlocked ? undefined : () => onToggle(district.id)}
              onMouseEnter={onHover ? () => onHover(district.id) : undefined}
              onMouseLeave={onHover ? () => onHover(null) : undefined}
            >
              {/* Native tooltip. Inside an aria-hidden subtree it is never
                  announced — the checkbox is what a screen reader reads — but
                  browsers still show it on hover, which is what turns an
                  unlabelled shape into a recognisable place. */}
              <title>{district.id}</title>
              <path className="district-map-shape" d={district.d} />
              <text
                className="district-map-number"
                x={district.labelX}
                y={district.labelY}
                fontSize={labelSize(district)}
                textAnchor="middle"
                dominantBaseline="central"
              >
                {district.num}
              </text>
            </g>
          );
        })}
      </svg>

      {/* Required by OSM's licence, not decoration — do not remove. */}
      <p className="district-map-credit">
        Hranice{' '}
        <a
          href="https://www.openstreetmap.org/copyright"
          target="_blank"
          rel="noreferrer"
        >
          © přispěvatelé OpenStreetMap
        </a>
      </p>
    </div>
  );
}

export default DistrictMap;
